# Generated by Django 5.0.2 on 2026-01-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active_ingredient', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
